# Generated by Django 5.2.8 on 2025-11-26 21:30

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_bio'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least(models.F('sender'), models.F('receiver')), django.db.models.functions.comparison.Greatest(models.F('sender'), models.F('receiver')), name='unique_friendship_pair'),
        ),
    ]
