# Generated by Django 5.2.8 on 2025-11-19 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='accounts.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_profile', 'name'), name='unique_hobby_per_user_profile')],
            },
        ),
    ]
