# Generated by Django 5.2.8 on 2025-12-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
