# Generated by Django 5.2.8 on 2025-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_bio'),
        ('hobbies', '0001_initial'),
        ('hobby_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('description__isnull', False), ('upload__isnull', False), _connector='OR'), name='require_description_or_upload'),
        ),
    ]
