# Generated by Django 5.2.8 on 2025-11-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_sessions', '0002_alter_session_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='friend_visibiilty',
            new_name='friend_visibility',
        ),
    ]
