# Generated by Django 5.2.8 on 2025-11-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_bio'),
        ('hobby_sessions', '0003_rename_friend_visibiilty_session_friend_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.userprofile'),
        ),
    ]
